site_name: Nutanix Cloud Platform
theme:
  name: material
  logo: images/nutanix-logo.png
  favicon: images/nutanix-logo.png
  pallete:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.sections

extra_css:
  - stylesheets/nx.css
markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
nav:

  - Home: index.md

  - Environment:
    - Environment Details: ncp1-environmentdetails.md

  - Nutanix Cloud Platform - Part1:
    - What is NCP: ncp1-whatisncp.md
    - Technology Overview: ncp1-technologyoverview.md
    - Storage Configuration: ncp1-storageconfiguration.md
    - Network Configuration: ncp1-networkconfiguration.md
  - Deploying and Managing Workloads:
    - Deploying Workloads: ncp1-deployingworkloads.md
    - Managing Workloads: ncp1-managingworkloads.md
  - Protecting Workloads:
    - Data Protection: ncp1-dataprotection.md

  - Nutanix Cloud Platform - Part2:
    - Nutanix Cloud Management: ncp2-nutanix-cloud-platform.md
    - Nutanix Cloud Operating Model: ncp2-cloud-operating-model.md
    - Setting Up the Environment:
      - Setting Up the Environment: ncp2-setting-up-environment.md
      - Category and Policy Management: ncp2-category-and-policy-mgmt.md
      - Identity and Access Management: ncp2-identity-and-access-mgmt.md
      - Projects: ncp2-projects.md
    - Build Your Cloud:
      - Build Your Cloud: ncp2-build-your-cloud.md
      - Self Service: ncp2-selfservice.md
    - Operate Your Cloud:
      - Operate Your Cloud: ncp2-operate-your-cloud.md
      - Reports: ncp2-reports.md
      - Capacity Planning: ncp2-capacity-planning.md
      - Inefficient VM Detection: ncp2-inefficient-vm-detection.md
      - Entity Browser, Search and Analysis: ncp2-entity-browser-search-analysis.md
      - Life Cycle Manager: ncp2-life-cycle-management.md
    - Govern Your Cloud:
      - Govern Your Cloud: ncp2-govern-your-cloud.md
      - Playbooks: ncp2-playbooks.md
      - Setting Up an Approval Policy: ncp2-setting-up-approval-policy.md
      - Launch an App from Marketplace: ncp2-launch-app-from-marketplace.md
      - Cost Governance: ncp2-cost-governance.md
      - Security Central: ncp2-security-central.md
    - Conclusion: ncp2-cloud-operating-conclusion.md

  - Nutanix Move:
    - Overview: migrate-workloads-overview.md
  - Setting up the Environment:
    - Overview: migrate-environment-overview.md
    - Category and Policy Management: migrate-environment-policies.md
    - Playbooks: migrate-environment-playbooks.md
    - Setup Takeaways: migrate-environment-setup-takeaways.md
  - Migrating Workloads:
    - Overview: migrate-workloads-overview.md
    - Setup Move: migrate-workloads-setup-move.md
    - Migrating VMs with Move: migrate-workloads-move-view-source-vm.md
    - Advanced VM Migrations: migrate-workloads-move-advanced-migration.md
    - Migrate at Scale: migrate-workloads-move-migrate-at-scale.md
    - Migrating Shares with Move: migrate-workloads-move-share.md
    - Migration Takeaways: migrate-workloads-migration-takeaways.md
  - Day 2 Management:
    - Overview: migrate-day2-overview.md
    - Nutanix Guest Tools: migrate-day2-guest-tools.md
    - IAM: migrate-day2-iam.md
    - Reports: migrate-day2-reports.md
    - Capacity Planning: migrate-day2-capacity-planning.md
    - Inefficient VM Detection: migrate-day2-inefficient-vm.md
    - Management Takeaways: migrate-day2-mgmt-takeaway.md
  - Conclusion:
    - Conclusion: migrate-conclusion.md
  - Flow Network Security:
    - Overview: flow-overview.md
  - Environment and App:
    - Prism Central Overview: flow-env-pc-overview.md
    - Flow Controller: flow-env-flow-controller.md
    - Categories: flow-env-categories.md
    - The Application: flow-env-application.md
  - Basic Security Policies:
    - Quarantine a VM: flow-basic-quarantine.md
    - Isolation Policies: flow-basic-isolation.md
  - Application Security Policies:
    - Application Policies: flow-app-app-policies.md
    - Monitor and Enforce the Policy: flow-app-monitor.md
    - Clone the Policy: flow-app-clone.md
    - Verify the Policy: flow-app-verify.md
  - Cyber Resilience:
    - Cyber Resilience: flow-cyber-resilience.md
  - NCM Self Service:
    - Getting Started: selfservice-gettingstart.md
  - Lab Setup:
    - Self Service Lab Setup: selfservice-lab-setup.md
  - IaaS Linux:
    - Self Service IaaS Linux: selfservice-linux.md
  - IaaS Windows:
    - Self Service IaaS Windows: selfservice-windows.md
  - DSL:
    - Self Service DSL: selfservice-dsl.md
  - Appendix:
    - Glossary: selfservice-appendix.md
