site_name: Nutanix Cloud Platform
theme:
  name: material
  logo: images/nutanix-logo.png
  favicon: images/nutanix-logo.png
  pallete:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.sections

extra_css:
  - stylesheets/nx.css
markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
nav:

  - Home: index.md

  - Environment:
    - Environment Details: ncp1-environmentdetails.md

  - Nutanix Cloud Platform Bootcamp- Part1:
    - Nutanix Cloud Platform:
      - What is NCP: ncp1-whatisncp.md
      - Technology Overview: ncp1-technologyoverview.md
      - Storage Configuration: ncp1-storageconfiguration.md
      - Network Configuration: ncp1-networkconfiguration.md
    - Deploying and Managing Workloads:
      - Deploying Workloads: ncp1-deployingworkloads.md
      - Managing Workloads: ncp1-managingworkloads.md
    - Protecting Workloads:
      - Data Protection: ncp1-dataprotection.md

  - Nutanix Cloud Platform Bootcamp - Part2:
    - Nutanix Cloud Management: ncp2-nutanix-cloud-platform.md
    - Nutanix Cloud Operating Model: ncp2-cloud-operating-model.md
    - Setting Up the Environment:
      - Setting Up the Environment: ncp2-setting-up-environment.md
      - Category and Policy Management: ncp2-category-and-policy-mgmt.md
      - Identity and Access Management: ncp2-identity-and-access-mgmt.md
      - Projects: ncp2-projects.md
    - Build Your Cloud:
      - Build Your Cloud: ncp2-build-your-cloud.md
      - Self Service: ncp2-selfservice.md
    - Operate Your Cloud:
      - Operate Your Cloud: ncp2-operate-your-cloud.md
      - Reports: ncp2-reports.md
      - Capacity Planning: ncp2-capacity-planning.md
      - Inefficient VM Detection: ncp2-inefficient-vm-detection.md
      - Entity Browser, Search and Analysis: ncp2-entity-browser-search-analysis.md
      - Life Cycle Manager: ncp2-life-cycle-management.md
    - Govern Your Cloud:
      - Govern Your Cloud: ncp2-govern-your-cloud.md
      - Playbooks: ncp2-playbooks.md
      - Setting Up an Approval Policy: ncp2-setting-up-approval-policy.md
      - Launch an App from Marketplace: ncp2-launch-app-from-marketplace.md
      - Cost Governance: ncp2-cost-governance.md
      - Security Central: ncp2-security-central.md
    - Conclusion: ncp2-cloud-operating-conclusion.md

  - Disaster Recovery Bootcamp:
    - Overview: dr-getting-started.md
    - Planned Failover: dr-planned-failover.md 
    - Unplanned Failover: dr-unplanned-failover.md

  - Nutanix Move Bootcamp:
    - Overview: migrate-nutanix-overview.md
    - Setting up the Environment:
      - Overview: migrate-environment-overview.md
      - Category and Policy Management: migrate-environment-policies.md
      - Playbooks: migrate-environment-playbooks.md
      - Setup Takeaways: migrate-environment-setup-takeaways.md
    - Migrating Workloads:
      - Overview: migrate-workloads-overview.md
      - Setup Move: migrate-workloads-setup-move.md
      - Migrating VMs with Move: migrate-workloads-move-view-source-vm.md
      - Create a Migration Plan: migrate-workloads-move-creating-migrate-plan.md
      - Migrate the VM: migrate-workloads-move-migrate-vm.md
      - Advanced VM Migrations: migrate-workloads-move-advanced-migration.md
      - Migrate at Scale: migrate-workloads-move-migrate-at-scale.md
      - Migrating Shares with Move: migrate-workloads-move-share.md
      - Configuring Nutanix Files: migrate-workloads-move-share-config-file.md
      - View Sopurce Share: migrate-workloads-move-share-view-share.md
      - Create Migration Plan: migrate-workloads-move-share-create-plan.md
      - Migrate share: migrate-workloads-move-share-migrate-share.md 
      - Migration Takeaways: migrate-workloads-migration-takeaways.md
    - Day 2 Management:
      - Overview: migrate-day2-overview.md
      - Nutanix Guest Tools: migrate-day2-guest-tools.md
      - IAM: migrate-day2-iam.md
      - Reports: migrate-day2-reports.md
      - Capacity Planning: migrate-day2-capacity-planning.md
      - Inefficient VM Detection: migrate-day2-inefficient-vm.md
      - Management Takeaways: migrate-day2-mgmt-takeaway.md
    - Conclusion:
      - Conclusion: migrate-conclusion.md
    
  - Flow Network Security Bootcamp:
    - Overview: flow-overview.md
    - Environment and App:
      - Prism Central Overview: flow-env-pc-overview.md
      - Flow Controller: flow-env-flow-controller.md
      - Categories: flow-env-categories.md
      - The Application: flow-env-application.md
    - Basic Security Policies:
      - Quarantine a VM: flow-basic-quarantine.md
      - Isolation Policies: flow-basic-isolation.md
    - Application Security Policies:
      - Application Policies: flow-app-app-policies.md
      - Monitor and Enforce the Policy: flow-app-monitor.md
      - Clone the Policy: flow-app-clone.md
      - Verify the Policy: flow-app-verify.md
    - Cyber Resilience:
      - Cyber Resilience: flow-cyber-resilience.md

  - NCM Self-Service Bootcamp:
    - Getting Started: selfservice-gettingstart.md
    - Lab Setup:
      - Self Service Lab Setup: selfservice-lab-setup.md
    - IaaS Linux:
      - Self Service IaaS Linux: selfservice-linux.md
    - IaaS Windows:
      - Self Service IaaS Windows: selfservice-windows.md
    - DSL:
      - Self Service DSL: selfservice-dsl.md
    - Appendix:
      - Glossary: selfservice-appendix.md

  - Nutanix Unified Storage Bootcamp:
    - Getting Started: nus-getting-start.md
    - Lab Setup: nus-lab-setup.md
    - Files:
      - Create SMB Share: nus-files-smb.md
      - Create NFS Export: nus-files-nfs.md
      - File Blocking: nus-files-block.md
      - Multi-Protocol: nus-files-multi-protocol.md
    - File Analytics:
      - File System Scan: nus-analytics-filesystem-scan.md
      - Anomaly Rules: nus-analytics-anomaly.md
      - Ransomware: nus-analytics-ransomware.md
    - Objects:
      - Bucket, Users, And Access Control: nus-objects-buckets.md
      - Versioning and Access Control: nus-objects-version.md
      - CLI and Scripting: nus-objects-cli.md
      - Tiering: nus-objects-tiering.md
      - Multi-Protocol: nus-objects-multi-protocol.md
    - Bonus:
      - Peer Global File Service: nus-bonus.md

  - Nutanix Database Services (NDB) Bootcamp:
    - Getting Started: ndb-getting-started.md
    - PostgreSQL:
      - Database Recovery: ndb-postgresql-dr.md
      - Database Provisioning and Patching: ndb-postgresql-provision.md
      - Create and Manage Clones: ndb-postgresql-create-manage.md
      - Takeaways: ndb-postgresql-takeaways.md
    - Optional Labs:
      - NDB REST API Explorer: ndb-postgresql-api.md
    - Appendix:
      - Glossary: ndb-appendix-glassary.md 

  - NKP Bootcamp:
    - Overview: nkp-bootcamp.md
    - Introduction:
      - Overview: nkp-intro.md
      - Setup: nkp-intro-setup.md
      - Navigating the labs: nkp-intro-navigating.md
      - Deploy Admin VM (LAB):
        - Overview: nkp-intro-deploy-admin-vm.md
        - VM Creation: nkp-intro-deploy-vm-creation.md
        - Connect to Web IDE: nkp-intro-connect-ide.md
      - Deploy NKP (Optional):
        - Overview: nkp-intro-deploy-nkp.md
        - Install NKP CLI: nkp-intro-deploy-nkp-cli.md
        - Create NKP Cluster: nkp-intro-deploy-nkp-cluster.md
        - Argument-based CLI installation: nkp-intro-deploy-nkp-cluster-cli.md
      - Takeaways: nkp-intro-takeaways.md
    - Fundamentals:
      - Overview: nkp-fundamentals.md
      - NKP Quick Tour: nkp-fundamentals-tour.md
      - Deploy and expose an app (LAB):
        - Overview: nkp-fundamentals-deploy.md
        - Accessing the shared NKP environment: nkp-fundamentals-deploy-access.md
        - Using kubectl to Create a Deployment: nkp-fundamentals-deploy-create-dp.md
        - Using a Service to Expose Your App: nkp-fundamentals-deploy-expose.md
      - Expose app on production (LAB):
        - Overview: nkp-fundamentals-expose.md
        - Load Balancer: nkp-fundamentals-expose-lb.md
        - Ingress: nkp-fundamentals-expose-ingress.md
      - Preparing for multi-tenancy:
        - Overview: nkp-fundamentals-multi.md
        - NKP Workspaces: nkp-fundamentals-multi-ws.md
        - NKP Projects: nkp-fundamentals-multi-proj.md
      - Persistent storage (LAB):
        - Overview: nkp-fundamentals-storage.md
        - StorageClass with Nutanix CSI: nkp-fundamentals-storage-csi.md
        - Block storage with Nutanix Volumes: nkp-fundamentals-storage-block.md
        - File storage with Nutanix Files: nkp-fundamentals-storage-file.md
      - Takeaways: nkp-fundamentals-takeaways.md
    - Observability:
      - Overview: nkp-observ.md
      - Visualizing platform metrics (LAB): nkp-observ-metrics.md
      - Platform analytics (LAB): nkp-observ-analytics.md
      - Cost visibility (LAB): nkp-observ-cost.md
      - Takeaways: nkp-observ-takeaways.md
    - Automation:
      - Overview: nkp-automation.md
      - Set up GitOps Deployment (LAB): nkp-automation-gitops.md
      - Access the Application: nkp-automation-gitops-access.md
      - Automate Multicluster App Deployments (LAB): nkp-automation-multicluster.md
    - Conclusion:
      - Conclusion: nkp-conclusion.md
    - Optional Labs:
      - Business Continuity and Disaster Recovery with NDK: nkp-option-ndk.md

  - NAI Bootcamp:
    - Nutanix Enterprise AI: nai-welcome.md
    - Introduction:
      - Overview: nai-intro.md
      - Setup: nai-intro-setup.md
      - Navigating the labs: nai-intro-navigating.md
    - Fundamentals:
      - Overview: nai-fundamentals-overview.md
      - Review the NAI Interface: nai-fundamentals-interface.md
      - Logi in to Nutanix Enterprise AI: nai-fundamentals-login.md
      - Import an LLM:
        - Overview: nai-fundamentals-import-llm.md
        - Import Your First Model: nai-fundamentals-import-model.md
      - Create An Endpoint:
        - Overview: nai-fundamentals-endpoint.md
        - Create an Endpoint and API Key: nai-fundamentals-endpoint-create.md
        - Test the Endpoint: nai-fundamentals-endpoint-test.md
        - View The Endpoint Details: nai-fundamentals-endpoint-view.md
        - Creating Additional API Keys (Optional): nai-fundamentals-endpoint-keys.md
      - Takeaways: nai-fundamentals-takeaways.md
    - Application:
      - Overview: nai-application-overview.md
      - Create Your First Chatbot:
        - Overview: nai-application-chatbot.md
        - Gather Information: nai-application-chatbot-gather.md
        - Create a Blank Chatflow in Flowise: nai-application-chatbot-flowise.md
        - Add Nodes to Chatflow: nai-application-chatbot-addnode.md
        - Configure Nodes: nai-application-chatbot-confnode.md
        - Connect Nodes: nai-application-chatbot-connnode.md
        - Test Chatflow: nai-application-chatbot-test.md
        - Configure Shared Endpoint: nai-application-chatbot-shared.md
      - Configure RAG:
        - Overview: nai-application-rag.md
        - Obtain Object Store URL and Credentials: nai-application-rag-store.md
        - Upload Document to Object Store: nai-application-rag-upload.md
        - Configure Embeddings and Vector Store: nai-application-rag-vector.md
        - Configure Chatflow: nai-application-rag-chatflow.md
        - Test the Chatbot: nai-application-rag-test.md
      - Takeaways: nai-application-takeaways.md
    - Conclusion:
      - Conclusion: nai-conclusion.md
    - Appendix:
      - Glossary: nai-appendix-glossary.md
      - Flowise Chatflows: nai-appendix-flowise.md
      - Types of Large Language Models: nai-appendix-typellm.md
          
  - Extend To Edge:
    - Getting Started: edge-getting-started.md
    - Lab:
      - Scenario 1 - Setting Up AWS:
        - Configure AWS: edge-lab-scenario1-setupaws.md
        - VPN Connectivity: edge-lab-scenario1-vpn.md
      - Scenario 2 - Setting Up Layer 2:
        - Overview & Pre-reqs: edge-lab-scenario2-overview.md
        - Deploy Local Gateways: edge-lab-scenario2-localgw.md
        - Deploy Remote Gateways: edge-lab-scenario2-remotegw.md
        - Extend Layer 2 Subnet: edge-lab-scenario2-layer2.md
      - Scenario 3 - DR:
        - Overview: edge-lab-scenario3-overview.md
        - Definitions: edge-lab-scenario3-def.md
        - Setup: edge-lab-scenario3-setup.md
        - Create Category & Associate VM: edge-lab-scenario3-cat.md
        - Create a Protection Policy: edge-lab-scenario3-protect.md
        - Create a Recovery Plan: edge-lab-scenario3-recover.md
        - Failover: edge-lab-scenario3-failover.md
    - Conclusion: edge-conclusion.md 